name: build-macos

on:
  push:
    branches: [ "mcicd-test" ]
  pull_request:

jobs:
  build-macos:
    timeout-minutes: 5
    runs-on: macos-14
    strategy:
      matrix:
        arch: [x86_64, arm64]
        pow_version: [0.2.2]

    steps:
    - name: Install dependencies
      run: |
        brew install curl git cmake automake autoconf libtool pkg-config
        curl -sL https://codeload.github.com/bitbi-core/pow/zip/refs/tags/v${{ matrix.pow_version }} -o pow.zip
        POW_HOME=$HOME/pow
        mkdir -p $POW_HOME
        unzip pow.zip -d $POW_HOME
        cd $POW_HOME/pow-${{ matrix.pow_version }}
        mkdir build
        cd build
        ARCH = ${{ matrix.arch }}
        cmake -DCMAKE_OSX_ARCHITECTURES=$(ARCH) \
          -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_SYSTEM_PROCESSOR=$(ARCH) \
          -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \
          -DCMAKE_C_FLAGS="-target $(ARCH)-apple-macos11.0" \
          -DCMAKE_CXX_FLAGS="-target $(ARCH)-apple-macos11.0" \
          -DCMAKE_EXE_LINKER_FLAGS="-target $(ARCH)-apple-macos11.0" ..

        make -j$(sysctl -n hw.logicalcpu)
        ls $POW_HOME/pow-${{ matrix.pow_version }}/build

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Miner
      run: |
        export ACLOCAL_PATH="$(pwd)/m4:$ACLOCAL_PATH"
        echo $ACLOCAL_PATH
        ./autogen.sh
        ./nomacro.pl
        POW_HOME=$HOME/pow/pow-${{ matrix.pow_version }}
        ls $POW_HOME
        ls $POW_HOME/build
        ./configure CPPFLAGS="-I$POW_HOME/src" LIBS="-L$POW_HOME/build -lrandomx -lcurl" \
                    CFLAGS="-arch ${{ matrix.arch }}" CXXFLAGS="-arch ${{ matrix.arch }}" \
                    LDFLAGS="-arch ${{ matrix.arch }}"
        make -j$(sysctl -n hw.logicalcpu)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-14-${{ matrix.arch }}
        path: ./minerd