name: build-macos

on:
  push:
    branches: [ "mcicd-test" ]
  pull_request:

jobs:
  build-macos:
    timeout-minutes: 5
    runs-on: macos-14
    strategy:
      matrix:
        arch: [x86_64, arm64]
        pow_version: [0.2.2]

    steps:
    - name: Set up environment
      run: |
        echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
        echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        if [ "${{ matrix.arch }}" == "x86_64" ]; then
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ~/.bash_profile
          eval "$(/usr/local/bin/brew shellenv)"
          arch -x86_64 brew install curl git cmake automake autoconf libtool pkg-config llvm openssl
        else
          brew install curl git cmake automake autoconf libtool pkg-config llvm openssl
        fi

    - name: Build pow dependency
      run: |
        curl -sL https://codeload.github.com/bitbi-core/pow/zip/refs/tags/v${{ matrix.pow_version }} -o pow.zip
        POW_HOME=$HOME/pow
        mkdir -p $POW_HOME
        unzip pow.zip -d $POW_HOME
        cd $POW_HOME/pow-${{ matrix.pow_version }}
        mkdir build
        cd build
        ARCH=${{ matrix.arch }}
        cmake -DCMAKE_OSX_ARCHITECTURES=$ARCH \
          -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_SYSTEM_PROCESSOR=$ARCH \
          -DCMAKE_OSX_SYSROOT=$SDKROOT \
          -DCMAKE_C_FLAGS="-arch $ARCH" \
          -DCMAKE_CXX_FLAGS="-arch $ARCH" \
          -DCMAKE_EXE_LINKER_FLAGS="-arch $ARCH" ..
        make -j$(sysctl -n hw.logicalcpu)
        ls $POW_HOME/pow-${{ matrix.pow_version }}/build

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Miner
      run: |
        export ACLOCAL_PATH="$(pwd)/m4:$ACLOCAL_PATH"
        echo $ACLOCAL_PATH
        ./autogen.sh
        ./nomacro.pl
        POW_HOME=$HOME/pow/pow-${{ matrix.pow_version }}
        ls $POW_HOME
        ls $POW_HOME/build
        if [ "${{ matrix.arch }}" == "x86_64" ]; then
          export PATH="/usr/local/opt/curl/bin:$PATH"
          export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LDFLAGS="-L/usr/local/opt/curl/lib -L/usr/local/opt/openssl/lib"
          export CPPFLAGS="-I/usr/local/opt/curl/include -I/usr/local/opt/openssl/include"
        else
          export PATH="/opt/homebrew/opt/curl/bin:$PATH"
          export PKG_CONFIG_PATH="/opt/homebrew/opt/curl/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LDFLAGS="-L/opt/homebrew/opt/curl/lib -L/opt/homebrew/opt/openssl/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/curl/include -I/opt/homebrew/opt/openssl/include"
        fi
        export CC="clang -arch ${{ matrix.arch }}"
        export CXX="clang++ -arch ${{ matrix.arch }}"
        ./configure CPPFLAGS="$CPPFLAGS -I$POW_HOME/src" LIBS="-L$POW_HOME/build -lrandomx -lcurl" \
                    CFLAGS="-arch ${{ matrix.arch }}" CXXFLAGS="-arch ${{ matrix.arch }}" \
                    LDFLAGS="$LDFLAGS -arch ${{ matrix.arch }}"
        make -j$(sysctl -n hw.logicalcpu)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-14-${{ matrix.arch }}
        path: ./minerd